
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

config_editor:

#device_tracker:
#  - platform: bluetooth_le_tracker
    #track_new_devices: true

http:
 server_port: 9000


telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
      - !secret telegram_chat_id_maria

notify:
  - platform: telegram
    name: "ha_notificator_denis"
    chat_id: !secret telegram_chat_id
  - platform: telegram
    name: "ha_notificator_maria"
    chat_id: !secret telegram_chat_id_maria
  - platform: group
    name: "denis&maria"
    services:
      - service: ha_notificator_denis
      - service: ha_notificator_maria
    

panel_custom:
  - name: devices
    sidebar_title: devices
    sidebar_icon: mdi:devices
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/devices/dashboard"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
  - name: automations
    sidebar_title: automations
    sidebar_icon: mdi:home-automation
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/automation/dashboard"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

generic_hygrostat:
  - name: Увлажнитель термостат гостиная
    humidifier: humidifier.deerma_jsq2g_b61d_humidifier
    target_sensor: sensor.temperatura_gostinaia_humidity
    min_humidity: 40
    max_humidity: 60
    target_humidity: 55
    dry_tolerance: 3
    wet_tolerance: 0
    device_class: "humidifier"
    min_cycle_duration:
      seconds: 60
    keep_alive:
      minutes: 3
    initial_state: true
    away_humidity: 35
    away_fixed: True
    sensor_stale_duration: 00:15:00
  - name: Увлажнитель термостат детская
    humidifier: humidifier.deerma_jsq2g_b5c1_humidifier
    target_sensor: sensor.temperatura_detskaia_humidity
    min_humidity: 40
    max_humidity: 60
    target_humidity: 55
    dry_tolerance: 3
    wet_tolerance: 0
    device_class: "humidifier"
    min_cycle_duration:
      seconds: 60
    keep_alive:
      minutes: 3
    initial_state: true
    away_humidity: 35
    away_fixed: True
    sensor_stale_duration: 00:15:00