
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

config_editor:

device_tracker:
  - platform: bluetooth_le_tracker
    #track_new_devices: true

http:
 server_port: 9000


timer:
  laundry:
    name: asd-zxc
    duration: "00:01:00"

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - platform: telegram
    name: "ha_notificator_denis"
    chat_id: !secret telegram_chat_id