blueprint:
  name: Light for motion with timers (temp)
  description: Advanced with timers
  domain: automation
  input:
    motion_trigger:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    light_switch:
      name: Light switch
      selector:
        target:
          entity:
          - domain:
            - light
            - switch

    timer_motion:
      name: Timer for motion
      selector:
          entity:
            filter:
              domain: timer

    timer_motion_duration:
      name: Timer motion duration
      default: 300
      selector:
        number:
          min: 10
          max: 1800
          step: 1
          unit_of_measurement: seconds
          mode: slider

    timer_manual_off:
      name: Timer manual off
      description: Timer delay motion detection after manual switch off
      selector:
        entity:
          filter:
            domain: timer

    timer_manual_off_duration:
      name: Timer manual off duration
      default: 60
      selector:
        number:
          min: 1
          max: 600
          step: 1
          unit_of_measurement: seconds
          mode: slider

    off_by_timeout:
      name: Light is off by timeout
      selector:
        entity:
          filter:
            domain:
              input_boolean
    after_time:
      name: Start Time
      description: Set the start time
      default: 00:00:00
      selector:
        time: {}

    before_time:
      name: End Time
      description: Set the end time
      default: 00:00:00
      selector:
        time: {}

    light_sensor:
      name: Light sensor
      default: []
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - illuminance

    max_light_lux:
      name: Maximum lux to enable
      description: Lower than value should enable the light
      default: 20
      selector:
        number:
          min: 0
          max: 500
          step: 10
          unit_of_measurement: LUX
          mode: slider


mode: restart
max_exceeded: silent

variables:
  light_sensor: !input light_sensor
  max_light_lux: !input max_light_lux
  light_switch: !input light_switch
 # light_entities: '{{ expand(light_switch.entity_id) | selectattr("domain","eq","light") | map(attribute="entity_id") | list }}'
 # switch_entities: '{{ expand(light_switch.entity_id) | selectattr("domain", "eq", "switch") | map(attribute="entity_id") | list }}'
 # light_entities: '{{ expand(light_switch.entity_id) | selectattr(''domain'', ''eq'',
 #   ''light'') | map(attribute=''entity_id'') | list }}'
 # switch_entities: '{{ expand(light_switch.entity_id) | selectattr(''domain'', ''eq'',
 #   ''switch'') | map(attribute=''entity_id'') | list }}'


trigger:
  - platform: state
    id: motion
    entity_id: !input motion_trigger
    from: 'off'
    to: 'on'

  - platform: event
    id: timer_motion_finished
    event_type: timer.finished
    event_data:
      entity_id: !input timer_motion 

  - platform: state
    id: light_on
    entity_id: '{{ light_switch.entity_id }}'
    from: "off"
    to: "on"




condition:


action:
