blueprint:
  name: Light for motion with timers
  description: Advanced with timers
  domain: automation
  input:
    motion_trigger:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    light_switch:
      name: Light switch
      selector: 
        entity:
          filter:
            domain:
              - light
              - switch

    time_motion_delay:
      name: Time Delay motion
      default:
        minutes: 15
      selector:
        duration:

    time_manual_off_delay:
      name: Time Delay manual off
      default:
        minutes: 1
      selector:
        duration:

    timer_no_motion:
      name: Timer
      selector:
          entity:
            filter:
              domain: timer

mode: restart
max_exceeded: silent

variables:
  off_by_timeout: 23
# motion_trigger: !input motion_trigger
# light_switch: !input light_switch
# time_motion_delay: !input time_motion_delay
# time_manual_off_delay: !input time_manual_off_delay
#  timer_select: !input timer_no_motion


trigger:
  - platform: state
    id: motion
    entity_id: !input motion_trigger
    from: 'off'
    to: 'on'  

  - platform: event
    id: timer_finished
    event_type: timer.finished
    event_data:
      entity_id: !input timer_no_motion 

  - platform: state
    id: light_on
    entity_id: !input light_switch    
    from: "off"
    to: "on"

  - platform: state
    id: light_off
    entity_id: !input light_switch    
    from: "on"
    to: "off"


condition:


action:
  - choose:
#---------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: light_on
        sequence:
          - service: notify.ha_notificator_denis
            data:
              message: "is on"
          - service: timer.start
            data:
              duration: !input time_motion_delay
            target:
              entity_id: !input timer_no_motion
#---------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: light_off
        sequence:
          - service: notify.ha_notificator_denis
            data:
              message: "is off {{ off_by_timeout }}"
          - service: timer.finish
            data: {}
            target:
              entity_id: !input timer_no_motion
#---------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          - service: notify.ha_notificator_denis
            data:
              message: finished {{ off_by_timeout }}
          - service: switch.turn_off
            data: {}
            target:
              entity_id: !input light_switch
#---------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: motion
        sequence:
          - service: notify.ha_notificator_denis
            data:
              message: motion
          - service: switch.turn_on
            data: {}
            target:
              entity_id: !input light_switch
          - service: timer.start
            data:
              duration: !input time_motion_delay
            target:
              entity_id: !input timer_no_motion
          - service: logbook.log
            data:
              message: >
                {% set off_by_timeout = 42 %}
                {{ off_by_timeout }}
#---------------------------------------------------------------


