blueprint:
  name: Light for motion with timers
  description: Advanced with timers
  domain: automation
  input:
    motion_trigger:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    light_switch:
      name: Light switch
      selector: 
        entity:
          filter:
            domain:
              - light
              - switch

    timer_no_motion:
      name: Timer for motion
      selector:
          entity:
            filter:
              domain: timer

    timer_manual_off:
      name: Timer manual off
      description: Timer delay motion detection after manual switch off
      selector:
        entity:
          filter:
            domain: timer

    off_by_timeout:
      name: Light is off by timeout
      selector:
        entity:
          filter:
            domain:
              input_boolean


mode: restart
max_exceeded: silent

#variables:
 # temp2: '23'
#  v_off_by_timeout: !input off_by_timeout
# motion_trigger: !input motion_trigger
# light_switch: !input light_switch
# time_motion_delay: !input time_motion_delay
# time_manual_off_delay: !input time_manual_off_delay
#  timer_select: !input timer_no_motion


trigger:
  - platform: state
    id: motion
    entity_id: !input motion_trigger
    from: 'off'
    to: 'on'

  - platform: event
    id: timer_motion_finished
    event_type: timer.finished
    event_data:
      entity_id: !input timer_no_motion 

  - platform: state
    id: light_on
    entity_id: !input light_switch
    from: "off"
    to: "on"

  - platform: state
    id: light_off
    entity_id: !input light_switch
    from: "on"
    to: "off"


condition:


action:
  - choose:
#---------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: light_on
        sequence:
          - service: timer.start
            data: {}
            target:
              entity_id: !input timer_no_motion
          - service: timer.cancel
            data: {}
            target:
              entity_id: !input timer_manual_off
          - service: input_boolean.turn_off
            target:
              entity_id: !input off_by_timeout
#---------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: light_off
        sequence:
          - service: timer.start
            data: {}
            target:
              entity_id: !input timer_manual_off
          - service: timer.cancel
            data: {}
            target:
              entity_id: !input timer_no_motion
#---------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: timer_motion_finished
          - condition: state
            entity_id: !input light_switch
            state: "on"
        sequence:
         - service: input_boolean.turn_on
           target:
             entity_id: !input off_by_timeout
         - service: switch.turn_off
           data: {}
           target:
             entity_id: !input light_switch 
#---------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: motion
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: !input light_switch
#---------------------------------------------------------------
